### ISSUE TITLE
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url:

### ISSUE THREAD

**Issue by rtotheb2000** [rajatomar788/pywebcopy#18] opened 2019-10-14 08:39 UTC
https://webcache.googleusercontent.com/search?q=cache:xmUxEzUZmaMJ:https://www.westermann.de/artikel/978-3-507-84567-1/Faktor-Mathematik-fuer-die-Sekundarstufe-I-in-Berlin-Ausgabe-2006-Lehrermaterial-7+&cd=1&hl=de&ct=clnk&gl=de

I can not use `save_webpage()` for the above URL although I am using `bypass_robots=True`.

**Comment by rajatomar788** [comment] 2019-10-21 05:26
What exactly happened!
Show some logs and the result it gave.

**Comment by kkkelvinkk** [comment] 2019-11-30 14:12
I think I experience the same problem when using "bypass_robots" parameters and python3.

**Comment by rajatomar788** [comment] 2019-11-30 14:41
The issue is that the google restricts access from bots or scripts. Thus the error 403.
Use of the latest version of chrome user-agent should fix this issue.

**Comment by kkkelvinkk** [comment] 2019-11-30 14:46
I am not accessing google, and pywebcopy append the " / %22 characters when crawler. I am trying save_webpage command, and I will send the webpage to you via email because I am trying locating your email address.

Would you please suggest any way to perverse the original file name when save_webpage ? Thanks a lot.

**Comment by rajatomar788** [comment] 2019-11-30 14:47
Send me the link in the email along with the log file if you please.

**Comment by rajatomar788** [comment] 2019-12-07 13:16
Its fixed in the version 6.1.0. I am closing this issue.

**Closed by rajatomar788** 2019-12-07 13:16 UTC

**Comment by harjotkaur1** [comment] 2020-01-04 23:02
What was the final solution? I am facing the same issue

**Comment by tomaszsibilski** [comment] 2022-01-05 20:40
I'm facing the same issue. Could you please double-check, please, if the issue is fixed? 

from pywebcopy import save_webpage

_url = 'https://www.oddschecker.com/football'
_name = "testing"
_download_folder = 'c://'    

save_webpage(
      url=_url,
      project_folder=_download_folder,
      project_name=_name,
      debug=True
 )

PS. Thanks for letting us have the library. It's a great idea.

**Comment by tomaszsibilski** [comment] 2022-01-05 20:58
Is there any way to change the name of the user-agent to something more generic, because some websites don't accept bots?
It looks like in the path there is a 'bot' what might be a reason for the error: 
_HTTPError: 403 Client Error: Forbidden for url: https://www.oddschecker.com/football_

**'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko/20100101 Firefox/70.0 PyWebCopyBot/6.3.0'**

**Comment by rajatomar788** [comment] 2022-01-26 12:44
Has anyone facing this with version 6.3.0 or above? If not then its site specific issue.

**Comment by rajatomar788** [comment] 2022-09-28 16:06
HTTP 403 is a authentication error meaning you would have to login or verify with the site before being able to see that particular page.

**Comment by snake-py** [comment] 2022-09-28 16:07
@rajatomar788 but I can visit the site without logging in, it seems to me that the request is blocked because it is identified as a bot.

**Comment by rajatomar788** [comment] 2022-09-28 16:09
Well you can try changing the user-agent string from the session or configuratin.

**Comment by snake-py** [comment] 2022-09-28 16:10
@rajatomar788 am I changing it correctly? I can try different user agents, but I am unsure if the way how I provide the user agent to the package is correct. 

```python
    kwargs = {'bypass_robots': True, 'http_headers': {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}}
    wp = pywebcopy.WebPage(**kwargs)
```

**Comment by rajatomar788** [comment] 2022-09-28 16:15
Yes this is one way of doing.

**Comment by kaganhazalkocdemir** [comment] 2023-03-01 12:02
Hi, currently, pywebcopy doesnt have Webpage. FYI
